[build-system]
requires = ["setuptools"]
build-backend = "setuptools.backends.legacy:BuildBackend"

[project]
name = "energystock-ai"
version = "0.1.0"
dependencies = [
    "kedro>=0.19.0",
    "kedro-datasets[pandas,parquet]>=1.0.0",
    "kedro-viz>=11.0.0",
    "pandas",
    "numpy",
    "scikit-learn",
    "yfinance",
    "requests",
    "joblib",
    "evidently",
    "streamlit",
    "python-dotenv",
    "mlflow",
    "fastapi",
    "uvicorn[standard]"
]

[tool.kedro]
package_name = "energystock_ai"
project_name = "energystock-ai"
kedro_init_version = "1.2.0"
tools = ""
example_pipeline = "false"
source_dir = "src"

[tool.kedro_telemetry]
project_id = "0ebae7ea38b64559bc29ec7558ec6c6d"
